Repository ES2-UFPI/TourMaker, pull requests merged in 2021-01, with the labels that each got.

#34 Integração com Realtime Database Issue #30
  APIs/Firebase.js
Labels: enhancement

#39 Nova hurística do roteiro automático #33
  Screens/RoteiroAutomaticoScreen.js
Labels: enhancement

#40 Anderson#28
  APIs/ReactMaps.js
  App.js
  Screens/DetalhesPDIScreen.js
  Screens/RoteiroManualScreen.js
Labels: enhancement

#43 Bug #41 corrigido: Erro ao finalizar criação de roteiro
  Screens/HomeScreen.js
  Screens/RoteiroAutomaticoScreen.js
  Screens/RoteiroManualScreen.js
  Screens/ScreensModules/CustomMapView.js
Labels: bugCorrection

#44 Implementado issue #32
  Screens/DetalhesPDIScreen.js
  Screens/ScreensModules/Blank_Star.png
  Screens/ScreensModules/Filled_Star.png
  Screens/ScreensModules/StarRating.js
Labels: enhancement

#45 Desc PDI no ControleRoteiro Implementada (#28)
  Screens/ControleRoteiroScreen.js
Labels: enhancement

#46 Correção de codigo para permanencia de dados Issue #31
  APIs/Firebase.js
Labels: bug

#47 Implementado Issue #28
  Screens/DetalhesPDIScreen.js
Labels: enhancement

#48 Merge da Dev para o Master, versão estável
  .travis.yml
  APIs/Firebase.js
  APIs/ReactMaps.js
  App.js
  README.md
  Screens/ControleRoteiroScreen.js
  Screens/DetalhesPDIScreen.js
  Screens/HomeScreen.js
  Screens/RoteiroAutomaticoScreen.js
  Screens/RoteiroManualScreen.js
  Screens/ScreensModules/Blank_Star.png
  Screens/ScreensModules/CustomMapView.js
  Screens/ScreensModules/Filled_Star.png
  Screens/ScreensModules/StarRating.js
  app.json
Labels: enhancement

#50 Correção bug #49
  Screens/DetalhesPDIScreen.js
Labels: bugCorrection

#51 Versão estável com bug fixado
  Screens/DetalhesPDIScreen.js
Labels: enhancement

#59 Implementado #56
  APIs/AsyncStorage.js
Labels: enhancement

#62 Interface para salvamento de roteiros #55 instalação de modulo #10
  Screens/ControleRoteiroScreen.js
  package-lock.json
  package.json
Labels: enhancement

#63 Fixed Issue #56
  APIs/AsyncStorage.js
Labels: bugCorrection

#65 Resolução do Bug #42
  APIs/AsyncStorage.js
  Screens/RoteiroAutomaticoScreen.js
Labels: bugCorrection

#66 Implementado Issue #52
  APIs/Firebase.js
  Screens/DetalhesPDIScreen.js
  Screens/ScreensModules/CustomTable.js
  Screens/ScreensModules/StarRating.js
Labels: enhancement

#67 Mayrongil #54
  APIs/Firebase.js
  App.js
  Header.js
  Screens/HomeScreen.js
  Screens/ScreensModules/TableButton.js
  assets/default-user-avatar.jpg
  package-lock.json
  package.json
Labels: enhancement

#68 Jest#61
  .travis.yml
  App.js
  CustomHeader.js
  Screens/ControleRoteiroScreen.js
  Screens/HomeScreen.js
  __test__/ControleRoteiroScreen.test.js
  __test__/DetalhesPDIScreen.test.js
  __test__/HomeScreen.test.js
  __test__/RoteiroAutomaticoScreen.test.js
  __test__/RoteiroManualScreen.test.js
  __test__/__snapshots__/ControleRoteiroScreen.test.js.snap
  __test__/__snapshots__/DetalhesPDIScreen.test.js.snap
  __test__/__snapshots__/HomeScreen.test.js.snap
  __test__/__snapshots__/RoteiroAutomaticoScreen.test.js.snap
  __test__/__snapshots__/RoteiroManualScreen.test.js.snap
  jestSetupFile.js
  package.json
  yarn-error.log
Labels: enhancement

#69 Implementada Issue #53
  APIs/Firebase.js
  Screens/DetalhesPDIScreen.js
Labels: enhancement

#71 Implementado rolagem de tela ( #70)
  Screens/ScreensModules/CustomTable.js
Labels: enhancement

#73 Resolução bug #72
  CustomHeader.js
Labels: bugCorrection

#75 fixado bug #74
  Screens/DetalhesPDIScreen.js
Labels: bugCorrection

#76 Criação de interface para uso de Roteiros Salvos Close #55
  App.js
  Screens/ControleRoteiroScreen.js
  Screens/HomeScreen.js
  Screens/SavedScreen.js
  package-lock.json
  package.json
Labels: enhancement

#77 Criação do teste para a tela SavedScreens.js #61
  __test__/ControleRoteiroScreen.test.js
  __test__/DetalhesPDIScreen.test.js
  __test__/RoteiroManualScreen.test.js
  __test__/SavedScreen.test.js
  __test__/__snapshots__/ControleRoteiroScreen.test.js.snap
  __test__/__snapshots__/DetalhesPDIScreen.test.js.snap
  __test__/__snapshots__/RoteiroAutomaticoScreen.test.js.snap
  __test__/__snapshots__/RoteiroManualScreen.test.js.snap
  __test__/__snapshots__/SavedScreen.test.js.snap
Labels: enhancement

#78 Seleçao de filtro adicionada. #60
  Screens/RoteiroAutomaticoScreen.js
Labels: enhancement

#79 Atualização snapshots dos testes #61
  __test__/__snapshots__/RoteiroAutomaticoScreen.test.js.snap
Labels: Testes
